version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    hostname: localhost
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: password
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/17/bin
      GOSU_VERSION: 1.17
      LANG: en_US.utf8
      PG_MAJOR: 17
      PG_VERSION: 17.4-1.pgdg120+2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: "no"  # Note: valid values are "no", "always", "on-failure", "unless-stopped"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: >
      start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KC_HOSTNAME_STRICT: false
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://pgvector:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
    ports:
      - "8082:8080"
    depends_on:
      - pgvector
    volumes:
      - ./src/main/resources/realm-export.json:/opt/keycloak/data/import/realm-export.json
    restart: "no"

volumes:
  pgdata:
