logging:
  level:
    dev.langchain4j: DEBUG
    org.springframework.web: INFO

spring:
  application:
    name: Doc2Chat
  security:
    oauth2:
      audience: account
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:8082/realms/Doc2Chat
        registration:
          oidc:
            client-id: web_client
            client-secret: web_client
            scope: openid, profile, email, offline_access # last one for refresh tokens

server:
  port: 8080


cors:
  allowed-origins:
    - "*"
  allowed-methods:
    - GET
    - PUT
    - POST
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  max-age: 1800

embedding-store:
  host: localhost
  port: 5432
  database: postgres
  user: postgres
  password: password
  table: documents
  use-index: true
  index-list-size: 100
  create-table: true
  drop-table-first: true

langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-3.5-turbo
      temperature: 0.7
    embedding-model:
      api-key: ${OPENAI_API_KEY}
      model-name: text-embedding-ada-002

docs.path: ""